Use a direct string instead of a variable
Fix compiler error when Debian hardening is used:
pam_pkcs11.c:810:4: error: format not a string literal and no format
arguments [-Werror=format-security]