Use a direct string instead of variable
Fix compiler errors when Debian hardening is used:
pam_pkcs11.c:198:3: error: format not a string literal and no format
arguments [-Werror=format-security]